name: Terraform CI/CD

on:
  pull_request:
    branches: [develop, release, main]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: "🔍 Terraform Validate & Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: infra/rds

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: infra/rds

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/rds

  # plan:
  #   name: "📖 Terraform Plan"
  #   runs-on: ubuntu-latest
  #   needs: validate
  #   if: github.event_name == 'pull_request'
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.6.0

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Terraform Init
  #       run: terraform init
  #       working-directory: infra/rds

  #     - name: Terraform Plan
  #       run: terraform plan -out=tfplan
  #       working-directory: infra/rds
  #       env:
  #         TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}

  #     - name: Save Terraform Plan Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: tfplan
  #         path: infra/rds/tfplan

#  apply:
#    name: "🚀 Terraform Apply"
#    runs-on: ubuntu-latest
#    needs: plan
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: 1.6.0
#
#      - name: Terraform Init
#        run: terraform init
#        working-directory: infra/rds
#
#      - name: Download Terraform Plan
#        uses: actions/download-artifact@v4
#        with:
#          name: tfplan
#          path: infra/rds/
#
#      - name: Terraform Apply
#        run: terraform apply -auto-approve tfplan
#        working-directory: infra/rds
